### ISSUE TITLE
Cannot Find Component Re-Sizable

### ISSUE THREAD

**Issue by ehubbell** [evocount/ember-resizable#155]
I get the following error when I attempt to load this addon after install:

**Error**
`Error: Compile Error: Cannot find component re-sizable`

**Template**
```handlebars
<ReSizable @width=200 @height=200>
   <h1>Testing</h1>
</ReSizable>
```

I have the following configuration:
```
ember-cli: 3.5.1
node: 8.9.4
```

**Update**
...Pretty sure this has to do with my ember-cli version not supporting ES Class syntax in templates (https://blog.emberjs.com/2018/12/13/ember-3-6-released.html). Lemme know if you think I'm correct. If so, you might update the minimum requirements section of the Readme. I'll try updating to 3.6 to test after I hear back.

**Comment by ttill** [comment]
I suspect this is related to your rather old version of ember-cli. 
Are you able to update to a more recent version or can you reproduce this in a clean project using ember-cli 3.5?

**Comment by ehubbell** [comment]
Ok, I've reproduced this in a clean project using ember-cli 3.5. At first, I was missing the `ember-lifeline` module. After installing the addon, I get the following error:

`Assertion Failed: computed expects a function or an object as last argument.`

**Comment by ttill** [comment]
Thanks for your thorough investigation. There are polyfills available for older versions of ember:
* ember-fn-helper-polyfill
* ember-on-modifier

So based on your analysis I would assume that this addon should work from 3.10 upwards if these two polyfills were included.

Regarding the error on computed properties: `ember-decorators-polyfill` already is a dependency and should polyfill this all the way down to some 2.x versions…

**Comment by ehubbell** [comment]
For sure! I kinda lost track of this and ended up rolling something on my own so I'm good to go :)

**Comment by ttill** [comment]
Hi,

0.4.5 was just released which moves `ember-lifeline` from devDeps to dependencies.
I noticed that `ember-fn-helper-polyfill` and `ember-on-modifier` are already included as devDeps. Maybe they have to be moved to dependencies as well.

**Comment by ttill** [comment]
0.4.6 was just released with the polyfills moved from devDeps to dependencies.
