### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by boris-petrov** [evocount/ember-resizable#359]
Hi, thanks for the *great* plugin!

Running on Ember 3.21 (and I believe some older versions too) leads to a `ember-lifeline runDisposables is deprecated. Explicitly invoking disposables is no longer required.` warning. I *think* this has already been [fixed in ember-lifeline](https://github.com/ember-lifeline/ember-lifeline/pull/852) and I see that `ember-resizable` is already using the latest major version so I'm not sure why I'm seeing the warning. Any ideas?

The stack trace is pointing to `ReSizable.willDestroyElement` calling `runDisposables`.

P.S. Actually I think this is a warning from `ember-lifeline` itself so most of what I wrote above is irrelevant - the Ember version perhaps doesn't matter and this is something that must be fixed in `ember-resizable`.

**Comment by ttill** [comment]
Thanks for reporting!
