### ISSUE TITLE
Resize gets stuck when initiated by a right click.

### ISSUE THREAD

**Issue by mikaellisselgard** [evocount/ember-resizable#72]
First of all, thanks for a great addon!

I've noticed that the resize gets stuck when it's initiated by a right click instead of a left click. The only way I can stop the resize after this is to reload the page:
![resize-bug](https://user-images.githubusercontent.com/9692812/57285622-e2eab400-70b3-11e9-9d6c-2d852c3adc10.gif)

I suggest not to initiate resize if a resizer element is right clicked. Something like:
```
if (event.button === 2) {
  return;
}
````
in the `_onResizeStart()` action.

What are your thoughts on this? Perhaps you have a different solution to the issue?

**Comment by ttill** [comment]
Thanks for your report! I will try to have a look at this tomorrow.

**Comment by ttill** [comment]
Just applied your proposed fix. Thanks again!

**Comment by mikaellisselgard** [comment]
@ttill Awesome! Thanks for a quick response and fix. :)
