### ISSUE TITLE
Overwrriten style

### ISSUE THREAD

**Issue by devotox** [evocount/ember-resizable#79]
Style object gets fully overwritten with new height & width but does not take into account that there could be other style attributes on the element. In my case the top & left attributes

**Comment by ttill** [comment]
Thanks for your feedback!
If you do not want `re-sizable` to manage its style, just do not set neither `width` nor `height` component properties. Then set the necessary style attributes yourself by listening to `onResize`.
Would this work for you?

**Comment by devotox** [comment]
Even without setting width and height the style still changes because
internally you have the computed property listening to element width and
element height

**Comment by ttill** [comment]
I just successfully tested the following:

```javascript
@computed('width', 'height')
get reStyle() {
  return `background-color: #f0f; width: ${this.width}px; height: ${this.height}px;`;
}

@action
onResize(direction, newDimensions/*, delta, element*/) {
  this.setProperties(newDimensions);
}
```

```hbs
<ReSizable
  style={{reStyle}}
  @onResize={{action "onResize"}}
>
  <h1>Resize me</h1>
</ReSizable>
```

**Comment by devotox** [comment]
Do i need to have a style for this to work then.

I have just this

{{#re-sizable
 id=id
 onResize=(action "resizeNode")
class=(concat "jsplumb-node " node.type)
directions=(array "right" "bottom" "bottomRight")
}}

Also I had to add ember on modifier and ember lifeline to my addon for this to work. Do you think you need those in dependencies rather than devDependencies

"Meeting all your software solutions needs"
Devonte Emokpae
Managing Director | DTOX Consulting

M: 07447903346
E: me@devonte.io

**Comment by devotox** [comment]
yup just adding style to the element worked thank you

"Meeting all your software solutions needs"
Devonte Emokpae
Managing Director | DTOX Consulting

M: 07447903346
E: me@devonte.io

**Comment by ttill** [comment]
I wonder how the overwritten style could bother you, if you were not setting in the component?

Could you please open another issue for the dependency issue. I will try to have a look at it in the next days. Thanks
